### ISSUE TITLE
leak of coff data in parseCOFF() due to missing call to Marshal.FreeHGlobal

### ISSUE THREAD

**Issue by JohnLaTwC** [trustedsec/CS_COFFLoader#1]
In `parseCOFF` a call to ` Marshal.AllocHGlobal` need an accompanying call to `Marshal.FreeHGlobal` on `unmanagedData` to clean up the allocation.

```diff
!            IntPtr unmanagedData = Marshal.AllocHGlobal(data.Length);   <<< need to call Marshal.FreeHGlobal when done
            Marshal.Copy(data, 0, unmanagedData, data.Length);
            byte* coff_data = (byte*)unmanagedData.ToPointer();
            coff_header = (COFF_FILE_HEADER*)coff_data;
```

https://github.com/trustedsec/CS_COFFLoader/blob/c7228c6698b8e982495fd514e65cac9abd8aee72/src/CoffParser.cs#LL199C44-L199C56

**Comment by snus-b** [comment]
Marshal.FreeHGlobal has been added.
